### ISSUE TITLE
mouse wheel scrolling of page causes frozen rows and columns to stay floating at their absolute positions and not stay "attached" to the table

### ISSUE THREAD

**Issue by degraeve** [yidas/js-freeze-table#13]
This issue seems to only be caused by mouse wheel "jumpy" scrolling.  When clicking the scrollbar slider, the frozen rows and columns stay "attached" to their tables.

FWIW, this is happening on a page with two tables with frozen header and first column.

**Comment by yidas** [comment]
Hi @degraeve,

Could you provide a sample code to help identifying this issue?

Regards

**Comment by degraeve** [comment]
https://jsfiddle.net/degraeve/g2fcrjph/

Apologies for the crufty code example.  This example doesn't seem to have the mouse wheel scrolling problem (might be something specific to jsfiddle), but it does have a problem when DOM elements are added to the page above the tables with frozen headers and columns.

To reproduce:

1. Scroll the tables horizontally and vertically.
2. Click a black value in the top table.  A form will appear above the tables.
3. The "frozen" rows and columns will remain in their absolute position and appear on top of the form that has been revealed.
4. Scrolling the page causes the "frozen" rows and columns to snap back into place.

As I reconstructed the example, I realized this may not be a bug in your library.  It's possible I'm not using the library correctly or there are conflicts between the library and 20 years of css and js cruft that is getting included on the page.

**Comment by yidas** [comment]
@degraeve,

Thank you for providing the example and the instructions.

You can try to block the body scrolling design and only allow the table to scroll.

Cheers!

**Comment by alessandro-newzoo** [comment]
I'm having the same issue, but I don't understand your workaround @yidas , could you please elaborate?

**Comment by alessandro-newzoo** [comment]
I've checked your demos and the behaviour unfortunately is the same:

![table](https://user-images.githubusercontent.com/47320294/64530104-a1da0900-d30c-11e9-9f1b-19f514ba542b.gif)

the `top` property is too slow to update, so there's always a lot of delay when scrolling up and down resulting in the sticky columns not staying attached to the rest of the table.

The framerate of the GIF doesn't allow to see the problem very well, but it's way more noticeable in real life.

**Comment by yidas** [comment]
@alessandro-newzoo,

The slow problem is due to computer performance, and the frozen column costs more performance.

You can try to use single freezeTable in a web page and see if it's faster on your device.

**Comment by alessandro-newzoo** [comment]
hi @yidas thanks for coming back. I understand that, but there's gotta be something wrong somewhere in the library's code. I have used other plugins that constantly update the top property and they never performed nearly as bad :(

This is how it looks like from mobile, and these are my mobile device specs (not exactly a potato):

CPU: Kirin 970
RAM: 4GB

![ezgif com-optimize (1)](https://user-images.githubusercontent.com/47320294/64849733-49f51800-d614-11e9-9721-8b71e020fee2.gif)

I even tried to remove all the JavaScript on my website, but it doesn't help at all :/

**Comment by yidas** [comment]
Hi @alessandro-newzoo,

Which plugin do you use for good performance?

**Comment by bobemoe** [comment]
Having the same issue, even on the demo page I'm seeing this:
![2020-02-22-150625_767x570_scrot](https://user-images.githubusercontent.com/2304970/75094732-edfccb00-5585-11ea-8722-4cd95d9243b3.png)
Its not just slow to catch up, it actually never fully slides into correct position.

Same as above, its fine with scrollbar and only a problem using mouse wheel.
