### ISSUE TITLE
headWrapStyles ignores border styles

### ISSUE THREAD

**Issue by jescampos** [yidas/js-freeze-table#14]
Hi,

I init a freeze table with the follow:

```
var freeze_table_pecas_obra_edit = new FreezeTable("#freeze_table_pecas_obra_edit", 
	{
		'scrollable': true,
		'freezeHead': true,
		'freezeColumn': true,
		'scrollBar': false,
		'namespace': 'freeze_table_pecas_obra_edit',
		'columnWrapStyles' : {'border-right':'1px solid black'}, 
		'headWrapStyles'   : {'border-right':'1px solid black', 'border-bottom':'1px solid black'},
		'backgroundColor'  : '#DEDEDE',
		'columnBorderWidth': 1
	});

```

But it does not respect the border styles. Check this printscreen:

![image](https://user-images.githubusercontent.com/13242887/65239157-3cd59e80-dad6-11e9-99d5-0a3ff22ae148.png)

I think that I'm not doing anything wrong....

**Comment by yidas** [comment]
Hi @jescampos,

Can you provide sample code such as JSFiddle?

**Comment by jescampos** [comment]
Hi,

I tried to create one but now the header is not fixed: https://jsfiddle.net/4Lp852hm/1/

Can you have a look please?

**Comment by yidas** [comment]
Hi @jescampos,

Can you indicate the problem?
The demo seems to work fine.

**Comment by jescampos** [comment]
In this example, more cleaner,  you can se it better: https://jsfiddle.net/0t4vkx1d/

FreezeTable ignores the border-right css in headWrapStyles configuration. It's supposed to each th in thead has a border.

`'headWrapStyles'   : {'border-right':'1px solid black', 'border-bottom':'1px solid black'},`

The border-bottom works just fine!

Thanks.

**Comment by yidas** [comment]
Hi @jescampos,

`headWrapStyles` doesn't take affect to each th, you can set them by static CSS.

**Comment by jescampos** [comment]
I has setting the css to the table id:

`#table_id th` 

For some how the css was not applied.

I changed the selector to the the freeze container (div) and, it's not perfect, but works!

Thanks for support.
