### ISSUE TITLE
Any way to hide a disabled scrollbar?

### ISSUE THREAD

**Issue by gsirin** [yidas/js-freeze-table#15]
Works great except the not needed scrollbar? Any way to hide this?
The options "scrollBar" and "scrollable" are set to false by default. What am I missing?

![2019-09-19 18_39_13-Window](https://user-images.githubusercontent.com/3208391/65263382-d3bd4d80-db0c-11e9-9056-7de5d3aae43b.png)

**Comment by yidas** [comment]
Hi @gsirin,

Can you provide the sample code such as JSFiddle?

**Comment by gsirin** [comment]
Hi Nick,
was able to fix my issue by simply setting"freezeColumn" to false.
