### ISSUE TITLE
column width changes on scroll when user does modification at runtime

### ISSUE THREAD

**Issue by chandni27ojha** [yidas/js-freeze-table#16]
Hi,
I am using this js lib for the freeze table functionality. My table is editable at runtime, when the user keeps adding a new line in a cell, the corresponding cell in the freezed column, the width increases, but as soon as I scroll (up, down or right) the width of the freezed cell is restored to its original size, even though the one with the data is still having the modified width.
Due to this the data is not correctly visible and confuses the user.

I am unable to upload the actual table so have tried explaining the issue with another image, can someone please help.
![freeze colum issue](https://user-images.githubusercontent.com/56718596/67764333-03d00880-fa4a-11e9-8d8a-7f79e65ba279.png)

**Comment by kosuha606** [comment]
Hello, did you try to call this:
```js
$('.freeze-table').freezeTable('resize');
```
or this:
```js
$('.freeze-table').freezeTable('update');
```
After your content changed.
