### ISSUE TITLE
Text inputs in header getting filled with wrong values

### ISSUE THREAD

**Issue by urwill** [yidas/js-freeze-table#18]
I tried this and it freezes my columns like a charm, but I have one problem which makes the whole thing useless for me. 
I have text inputs in my header to filter the table content. When I use the freeze column function on my table and perform a postback these text inputs get filled with: value + ',' + value
So when the text input was empty then the value becomes ','
When it for example was '123' then the value becomes '123,123' and so on.
How can I prevent this from happening?

Thanks in advance

**Comment by DirkOlten** [comment]
If you have Inputs inside a frozen table, these get cloned and exists twice.
This will help:
```
$(".example").freezeTable({ 'columnNum': 2, });
$('.yourform').submit(function(){
    freeze_Table_Update();
});
function freeze_Table_Update() {
	$('.clone-head-table-wrap tbody :input, .clone-column-table-wrap tbody :input, .tableFloatingHeader thead :input').attr('name', null);
	return true;
};

```
