### ISSUE TITLE
header position change (not fix) after scroll

### ISSUE THREAD

**Issue by azizsiran** [yidas/js-freeze-table#19]
header position change (not fix) after scroll
what a solution for this case..?
![freeze-table](https://user-images.githubusercontent.com/58875254/70845540-8e49bb80-1e82-11ea-8836-18743aff091d.png)

**Comment by chiahungwang** [comment]
You can try to set "scrollBarHeight" options.
```
$('#freeze-table').freezeTable({
    scrollBarHeight: window.innerWidth - document.documentElement.clientWidth
});
```
