### ISSUE TITLE
If I want my table to get a max-height the plugin seems lost

### ISSUE THREAD

**Issue by boucdur** [yidas/js-freeze-table#2]
Hi,

I have very long tables. I happennes that I want my table to have a max-height. That way the visitors don't have to scroll the whole table before looking at what follows in the page. They could just scroll outside the table to pass the table.
I tried to set a max-height:80vh on the table and it does nothing the style is ignored. The full table is shown.
I tried then to set a max-height:80vh on the container. The table head sticks to the screen instead of the container. The behavior is very buggy.

Am I missing something or is it the plugin that could be improved ?

Bye,

François

**Comment by yidas** [comment]
Hi,

So far this library limits to use free Y scroll that doesn't support scroll for `overflow-y`, the sticky head is for browser but not for that table container.

This issue could be the improved item in the future.

Thanks for your suggestion.

**Comment by boucdur** [comment]
Ok thanks for this answer
