### ISSUE TITLE
cannot using two freeze table in diffrent tabs

### ISSUE THREAD

**Issue by push32** [yidas/js-freeze-table#22]
I'm using freeze table combine with bootstrap tabs, and the tabs one is smooth running, but the second tabs responding but the css and scroll all nothing happens, please help me

**Comment by push32** [comment]
https://jsfiddle.net/push32/2h5kw14q/5/

**Comment by yidas** [comment]
Hi,

You need to initialize the freezeTable to the table after it shown, for example:
https://jsfiddle.net/sxdyfkvL/2/

Regards

**Comment by push32** [comment]
it's working now, thank you for brought this great repo to us

Cheers
