### ISSUE TITLE
Is it possible to have the shadow on the right side?

### ISSUE THREAD

**Issue by davalb** [yidas/js-freeze-table#23]
Is it somehow possible to display the shadow on the right as well (in case there is more content on the right)?
My problem is that sometimes it is not immediately visible that there is more content on the right to scroll to. That happens when the border of the view conincides with the border of a column. I love the shadow effect as a visual indication that there is more and would like to use it.
(BTW thanks for this awesome piece of software)

**Comment by yidas** [comment]
Dear @davalb,

Thank you for you appreciation

The shadow is used for fixed header and column on the top and left.
What do you mean by the shadow on the right?

Regards~

**Comment by davalb** [comment]
Dear @yidas ,

as you say, there is only a shadow on the top and left. It would be cool to have a shadow on the right as well (if there is more content) to indicate that there is more. (In my use-case it is often not easily discoverable that there is more content if the user scrolls.) 

This picture shows the situation

https://raw.githubusercontent.com/yidas/jquery-freeze-table/master/img/demonstration.png

Best, David

**Comment by davalb** [comment]
I mean in the picture it is immediately clear that there is more content to the right because of the scrollbar and because the content of the last visible column is cut off. In my use case the scrollbar only appears if I start scrolling and the edge of the viewport conincides often with the border or margin of a column, thus there is no good visiual indication of more content.

**Comment by yidas** [comment]
Dear @davalb,

I see.
But in this case, I think the right shadow will confuse the user, because the shadow represents a fixed block, but it does not mean that there is no end.

Maybe there is a better solution we can think.
Thank you

**Comment by davalb** [comment]
Dera @yidas,

I see, my understanding is now as follows: In a way the fixed columns or rows are "above" the rest of the page and are casting a shadow, while the scrollable table is on one level with the rest of the page. Is that correct?

The model I had in mind for my use-case is that the fixed columns and rows are level with the rest of the page and the scrollable table is so to say down in a well. In that model shadows represent all directions in which there is more data. (In order to stay in that metaphor: If you are looking down that well in an angle that doesnt allow you to see all that there is in a direction, the obscured data lies in the shadows.)

Is it possible to implement this as a seperate option? (To be clear, maybe we can do it as a PR. But I would like to have your insight first, before we attempt something futile.) Alternatively fixed scrollbars would also solve the problem.

**Comment by yidas** [comment]
Hi @davalb,

I think the fixed scrollbar way is better, but when will the scrollbar disappear?
(I have tested by both Windows and MacOS, the scrollbar is always there)

For the right shadow, I think it's ok, but it's hard to add the right shadow on the side.
You could PR with this effect and I will check it!

Thank you

**Comment by davalb** [comment]
HI @yidas,

I think it could be usefull (at least in my situation) to have a scrollbar that never disappears. Do you think that is possible?

I looked into implemententing the right shadow, but I have to admit that I cannot do it.

Thank you

**Comment by yidas** [comment]
Hi @davalb,

Could you provide your OS and browser that the scrollbar will disappear?

Cheers

**Comment by davalb** [comment]
Sure, I use a mac (Sierra 10.12.6) and Firefox 75

(just to be clear though: the scrollbar appears, when I start scrolling the table-data. After scrolling it disappears again.)

**Comment by yidas** [comment]
Hi @davalb ,

I think the problem can be solved by adjusting MacOS setting:
https://heresthethingblog.com/2015/03/10/mac-tip-macs-scroll-bars/

Cheers

**Comment by davalb** [comment]
H @yidas , 

indeed, that setting makes the scrollbars stay. Thank you. It is still a bit of a problem for our site, that people that have set this setting to "when scrolling" might never discover the horizontal scrollability of the tables, however I dont see how this problem could be solved. So I am closing this issue. Thanks a lot for your support!
