### ISSUE TITLE
Set top "50px" Offset to the freeze header table.

### ISSUE THREAD

**Issue by sayedrafeeq** [yidas/js-freeze-table#27]
Is there any option to set top Offset value for freeze table. ?

**Demo Example**

```
$("#table-first").freezeTable({
  'freezeOffset: 50,
});
```

**Comment by yidas** [comment]
Hi @sayedrafeeq,

All `<thead>` can be frozen on the top, you could have multiple rows in `<thead>`.

Cheers

**Comment by sayedrafeeq** [comment]
Hi @yidas, Thanks for your reply & wonderful plug-in.

I have fixed the issue.  Here is a updated code.

```
$("#table-first").freezeTable({
  'headWrapStyles': { 'top': '50px' }
});
```

**Comment by yidas** [comment]
Hi @sayedrafeeq,

Sorry for my misunderstanding and thank you for the sharing!

Best regards

**Comment by sayedrafeeq** [comment]
Is there any options to clone dublicate table instead of "top: 0;" to "top: 50px" ? Where I can change that option. Please let me know.?
