### ISSUE TITLE
Didn't work on jQuery 3.1

### ISSUE THREAD

**Issue by turtle-bi** [yidas/js-freeze-table#3]
Its didnt working on jQuery 3.1. But work good on jQuery 2.4

**Comment by yidas** [comment]
Thanks for reporting.

jQuery 3.1 support would be the milestone.

Please use jQuery version 1.11.0+ or 2 instead at the moment..

**Comment by yidas** [comment]
Hi @turtle-bi ,

The new release [1.1.1](https://github.com/yidas/jquery-freeze-table/releases) supports jQuery 3, you can try it!

Cheers.
