### ISSUE TITLE
Not working together with previous position sticky div

### ISSUE THREAD

**Issue by 0hwow** [yidas/js-freeze-table#34]
Hi

I can't figure out how to make the plugin work with a sticky top navbar. If I set the navbar's div to position sticky the table head doesn´t stick. If I set the top navbar to position fixed the table head overrides the navbar and sticks on top.

Thank you for your great work and support

Happy New Year

**Comment by yidas** [comment]
Hi @0hwow,

Hope you are doing well!

Have you try to set the option: `fixedNavbar`?
This option should get you working smoothly with your navbar.

Happy new year!

**Comment by 0hwow** [comment]
Solved

Thank you

:)
