### ISSUE TITLE
Plugin disables table sorting

### ISSUE THREAD

**Issue by 0hwow** [yidas/js-freeze-table#35]
I am using jquery-freeze-table together with jquery-tablesorter [https://mottie.github.io/tablesorter/docs/](url)

jquery-freeze-table is in table-head-only mode, thead freezes fine but disables sorting

Any help is greatly appreciated

Thank you :)

` 
  <script src="/tablesorter-master/dist/js/jquery.tablesorter.min.js"></script>
  <script src="/tablesorter-master/dist/js/widgets/widget-filter.min.js"></script>
  <script src="/tablesorter-master/dist/js/widgets/widget-pager.min.js"></script>

  
  <script id="js">
    $(function () {

      var $table = $('#table')
        .tablesorter({
          // keeps columns width when child row is expanded
          widthFixed: true,
          // third click on the header will reset column to default - unsorted
          sortReset: true,
          // initialize filter and pager widgets
          widgets: ["filter", "pager"],
          widgetOptions: {
            // Pager
            // if true, child rows will be counted towards the pager set size
            pager_countChildRows: false,
            // output default: '{page}/{totalPages}'
            // possible variables: {page}, {totalPages}, {filteredPages}, {startRow}, {endRow}, {filteredRows} and {totalRows}
            pager_output: '{startRow} - {endRow} de {totalRows} elementos',
            // if true, the table will remain the same height no matter how many records are displayed. The space is made up by an empty
            // table row set to a height to compensate; default is false
            pager_fixedHeight: true,

            //Search filter
            // Set this option to false to hide input search in each column
            filter_columnFilters: false,
            filter_saveFilters: true,
            // Set this option to false to make the searches case sensitive
            filter_ignoreCase: true,
            // Reset search
            filter_reset: '.reset'
          }
        });
      // Add this class to input search
      $.tablesorter.filter.bindSearch($table, $('.search'));
    });
  </script>
  
  <script>
    $(function () {

      // hide child rows
      $('.tablesorter-childRow td').hide();

      $(".tablesorter")
        .tablesorter({
          cssChildRow: "tablesorter-childRow"
        })

      // Toggle child row content (td), not hiding the row since we are using rowspan
      // Using delegate because the pager plugin rebuilds the table after each page change
      // "delegate" works in jQuery 1.4.2+; use "live" back to v1.3; for older jQuery - SOL
      $('.tablesorter').delegate('.toggle-childRow', 'click', function () {

        // use "nextUntil" to toggle multiple child rows
        // toggle table cells instead of the row
        $(this).closest('tr').nextUntil('tr:not(.tablesorter-childRow)').find('td').toggle();
        // in v2.5.12, the parent row now has the class tablesorter-hasChildRow
        // so you can use this code as well
        // $(this).closest('tr').nextUntil('tr.tablesorter-hasChildRow').find('td').toggle-childRow();

        return false;
      });

    });

  </script>
  
  <script>
    function toggleChevron(x) {
      x.classList.toggle("icon-close");
    }
  </script>

  
  <script src="/jquery-freeze-table-master/dist/js/freeze-table.min.js"></script>
  <script>
    $(document).ready(function () {

      $(".table-head-only").freezeTable({
        'freezeColumn': false,
      });

    });
  </script>`

**Comment by yidas** [comment]
Hi @0hwow ,

Would you create a demo using for example [JSFiddle](https://jsfiddle.net/) for better research?

Thanks!

**Comment by 0hwow** [comment]
Notice how when disabling freeze-table tablesorter works fine. Also, th tooltips are covered by the table header despite set z-index

Thank you very much!

**Comment by yidas** [comment]
Hi @0hwow ,

Thank you for the demo!

I think it is caused by the conflict of the table structure modification between these two plugins. It seems that the two plugins cannot be applied to the same table.

Best regards

**Comment by 0hwow** [comment]
Thank you!

Best regards
