### ISSUE TITLE
指定table表格高度，假如第一列固定，会出现以下问题

### ISSUE THREAD

**Issue by data2** [yidas/js-freeze-table#37]
<img width="1038" alt="屏幕快照 2023-12-10 下午11 00 57" src="https://github.com/yidas/jquery-freeze-table/assets/13504729/46248d28-22d7-4715-8766-6414cce368fa">

**Comment by yidas** [comment]
Hi @data2 ,

In that case, you could use `scrollable` options like:

```html
<div class="table-scrollable" style="height: 200px;">
  <table...

<script>
$(".table-scrollable").freezeTable({
  'scrollable': true,
});
```

Cheers

**Comment by data2** [comment]
sounds good,  iwill try later.
