### ISSUE TITLE
How can I run update table only when table scrolled by X

### ISSUE THREAD

**Issue by kosuha606** [yidas/js-freeze-table#4]
Is where any method to call update when user scrolled table by X? I have large table and now I call update every time when checkbox in fixed column changed and updation work very slow on my large table. My table has about 200 rows.

Maybe your plugin triggers some events when scrolling, or some other undocumented events?

PS. I think I finded triggering on 550 line of plugin, but I don't know how to use it.

**Comment by yidas** [comment]
Hi @kosuhin 

You got a very good point.

Maybe this library can provide a hook when fixed column first showing up to optimize your scenario.

You can try to trigger changes to fixed columns together instead of using `update`.

Thanks for your suggestion.

**Comment by yidas** [comment]
Hi @kosuhin 

You can try [version 1.1.5](https://github.com/yidas/jquery-freeze-table/releases/tag/1.1.5) with using `columnKeep` for your scenario to optimize the performance.

The example can be referred to [Freeze Column(s) Keep](https://yidas.github.io/jquery-freeze-table/#table-column-keep).

Cheers.

**Comment by kosuha606** [comment]
Hello, thanks you, Sory for delay,  I'll check new version in my task.
