### ISSUE TITLE
No option to restrict table Y Scroll

### ISSUE THREAD

**Issue by ljking20003** [yidas/js-freeze-table#5]
Hi,

Great plug in, it may be something i missing but i cant set a scroll on the height, if i do then the sticky head stops working.

i have a configurable record count table displayed on the screen, so if the user changes its to 100 records per screen they would be unable to find a record and scroll across due to the x scroll bar being right at the bottom.

tried overflow-y:scroll; max-height:500px;

its a shame as otherwise its a simple and great plug in.

**Comment by yidas** [comment]
Hi @ljking20003,

This plugin makes table RWD and ensures the height is expanded although you set the height for table or wrapper.

You can try to enable `scrollBar` for your usage.

**Comment by yidas** [comment]
Hi @ljking20003,

The scroll-able height has been supported since [version 1.2.0](https://github.com/yidas/jquery-freeze-table/releases/tag/1.2.0).

You can refer to the `scrollable` option.

Cheers.
