### ISSUE TITLE
On Safari, the first column disappears when you scroll all the way to the right with your demo.

### ISSUE THREAD

**Issue by dskilken** [yidas/js-freeze-table#6]
When I run your demo in Safari, and you scroll all the way to the right when the first column and header are frozen, the first column disappears.  It reappears when you scroll back to the left.  The problem doesn't appear in Chrome.  Any idea why this is happening?

**Comment by dskilken** [comment]
by the way - brilliant plugin!!  Thank you very much!!

**Comment by yidas** [comment]
Hi @dskilken,

Does other browser has the same problem such as Firefox? I don't have access to a safari browser for testing.

Thank you for your great support.

**Comment by dskilken** [comment]
It tests OK on Firefox and Chrome.  On Safari, the first column overlay disappears when you scroll beyond the right edge of the table.  I will do some more debugging to see if I can figure out why.
Thanks,
Dan

**Comment by yidas** [comment]
Can you help me to check that is your Safari the highest version?

Thanks!

**Comment by dskilken** [comment]
Hi Nick,
I am running Safari 12.0.3. the latest version

I think this is a problem with Safari letting javascript know if it is scrolling. As you scroll to the right, the plugin works fine.  As long as the table still has room to scroll to the right, clone-column-table-wrap is still visible.  Once you scroll past the last cell, the column overlay gets hidden.  

I am going to integrate your plugin into a bootstrap page today.  I will continue to debug this for you, and will let you know if I find a solution. It may have to do with the general page structure too.
   
I really appreciate your follow up on this.
Best regards,
Dan

**Comment by dskilken** [comment]
Hi Nick,
It works fine on safari on the phone and iPad.  This problem is unique on the version of Safari on the Mac.    Still working on this….

**Comment by yidas** [comment]
Hi @dskilken 

Thank you for your help and information!

I may get a Mac device for testing after a few days.

**Comment by dskilken** [comment]
Hi Nick,
I spent the day removing bootstrap-table and integrating your code.   I finished late last night.  Your implementation of freezing the first column and header are the best I have found on the web, and the performance is excellent.    I can confirm that my site implementation performs the same on Safari.  I will take a look at the scroll code today to see if this is a Safari bug.  It only appears on Safari on the Mac.  Scroll all the way to the right and the first column overlay gets hidden.
Thanks,
Dan

**Comment by dskilken** [comment]
Hi Nick,
I have spent most of the day debugging what is going on with Safari 12.0.3 on Mac OS.

The problem does not existing on Safari for the iPad or iPhone

I have verified that the scrolling position data is work fine on all browsers.  no difference in what you are receiving from the browser.

columnKeep is not a work around.  This option if set to true makes the first column disappear and never come back.

Over scroll on Safari to the right and both clone-head-table-wrap, and clone-column-table-wrap both disappear.   Then clone-head-table-wrap comes back, but not clone-column-table-wrap.  As you scroll back to the left, clone-column-table-wrap re-appears until you scroll all the way to the left.

Commenting out the code for Disable while isWindowScrollX, and the else function for detect for horizontal scroll does not affect the issue


 // Disable while isWindowScrollX
   //     if (that.isWindowScrollX)
     //      return;

        // Detect for horizontal scroll
        if ($(this).scrollLeft() > 0) {
            console.log('Scroll X:'+ $(this).scrollLeft());
          that.$columnTableWrap.css('visibility', 'visible');

        } else {

       //   that.$columnTableWrap.css('visibility', 'hidden');
        }

I think Safari’s processing of scrolling position may be much slower than the other browsers.  This would imply the need for throttling on mac OS X
The solution may be a strange CSS configuration and not actually be in the Javascript.  (These are the worst bugs to track down.)

I have not found a solution on the web.

I hope these notes help you.

Do you clone the CSS for the clone-head-table-wrap, and clone-column-table-wrap?   It looks like I am losing the CSS for the first column.   Header looks correct.
Thank you again for sharing your fantastic code,

Dan

**Comment by yidas** [comment]
Hi @dskilken,

The table in `clone-column-table-wrap` is cloned by original table, what is the missing CSS in your first column?

> On Safari, the first column overlay disappears when you scroll beyond the right edge of the table.

Do you mean that the freeze column is hidden when your scrollX is at the end of the right? (visible when ScrollX in the middle)

Thank you for your sharing!

**Comment by dskilken** [comment]
Hi Nick,

Yes, the first column overlay disappears when you scroll beyond the right edge of the table in Safari.   Yes, the freeze column is hidden (actually gets visibility; hidden.

Background Color is lost in the css for the overlay, and alignment in the first column of the table without the overlay is off, but let me work through the css today.  It could be problems I am generating in my own css.    I have a lot of classes applied to the first column.
Thanks,
Dan

**Comment by yidas** [comment]
Hi @dskilken,

For Background Color, you can set `backgroundColor` option to `false` for keeping your own table CSS with [version 1.1.6](https://github.com/yidas/jquery-freeze-table/releases/tag/1.1.6).

Cheers!

**Comment by dskilken** [comment]
Hi Nick,
Thank you for the update.
I tried these settings:

 //Freeze table header and first column on scroll
 $("#table-scroll").freezeTable({
  'shadow': true,
  'backgroundColor': false
});

opacity and colors are still not coming through right.  Colors in the first column overlay should be the same as the rows to the right.
This may be something weird in my css..so I will continue to work through it.   It is easy for me to just set css rules for your overlay too.
Thank you again for all your help,
Dan

**Comment by dskilken** [comment]
Hi Nick,
I think it is not cloning background colors to the first column overlay.   I know this is a hard thing to do because there is css on the rows as well as the cells.

thanks,
Dan

**Comment by yidas** [comment]
Hi @dskilken,

Your customized CSS for row backgroundColor must be defined from the outer div (Which is the div to apply freezeTable()).

Cheers

**Comment by dskilken** [comment]
Hi Nick,
I have a suggestion/enhancement request - 
I have a very tall header on my table.  Is it possible to set an option to have the sticky header hidden when the bottom of the table scrolls to the bottom of the header instead of the top of the screen?
Thanks,
Dan

**Comment by yidas** [comment]
Hi @dskilken,

I added it into milestone.

Thanks for your suggestion.

**Comment by yidas** [comment]
Hi @dskilken,

My Mac's Safari(12.0.3) is worked fine without any problem.

The only thing is that Safari can not scroll by mouse pointer, so I just use Arrow key to scroll.

Nick

**Comment by dskilken** [comment]
Hi Nick,
On my Mac, scrolling with the keyboard does not experience the problem either.   The problem appears when using the touchpad to scroll.
I’m running High Sierra 10.3.6.    I will upgrade this week to Mohave to see if the problem is still there.  It could be an interaction between the OS and the browser.
Thanks,
Dan

**Comment by yidas** [comment]
Hi @dskilken,

OK! 

Thank you!
