### ISSUE TITLE
table background color

### ISSUE THREAD

**Issue by veera1908** [yidas/js-freeze-table#7]
I need table background color like below image... is it possible..
![screenshot-192 168 0 50-2019 03 29-11-57-40](https://user-images.githubusercontent.com/47779880/55213663-f9cafa80-5219-11e9-96f6-82d734a98ff0.png)

**Comment by yidas** [comment]
Hi @veera1908,

The style of the table does not affect the freeze table library, you can just style your background color to your table then apply it by library.

**Comment by veera1908** [comment]
thank you very much i got it.... :)
