### ISSUE TITLE
Issue with dragtable pluggin.

### ISSUE THREAD

**Issue by UsmanJavedAttari** [yidas/js-freeze-table#8]
I am developing a large dynamic table and your plugin is great for fixing rows and columns of any table. I really appreciate, but it's issuing with a plugin called [dragtable](https://github.com/akottr/dragtable). The issue is that when I drag a column from one place to another and then scroll down, it clones the previous header and when I again scroll to the top issue fixes up but on fixing the table header it's not working. Can you help me out this issue?
**On page load table;**
![image](https://user-images.githubusercontent.com/38417879/55688609-c57ed900-5993-11e9-8de1-2b48df2f6d24.png)
**After moving some columns:**
![image](https://user-images.githubusercontent.com/38417879/55688621-efd09680-5993-11e9-98f6-4be8d69d23c1.png)
**After scrolling:**
![image](https://user-images.githubusercontent.com/38417879/55688630-0840b100-5994-11e9-8561-c3e5ff650764.png)
Check out that after page scroll the header resets.
I think you have to clone the latest one top row but it's cloning the row which is loaded with the `page-load event.` I have opened your plugin to check out what's going on in there, but I was unable to change because I am not so expert in JS.
Regards:
UsmanJavedAttari

**Comment by yidas** [comment]
Hi @UsmanJavedAttari,

You can try to call `update()` after dragtable is dragged. ([Update for Dynamic Content](https://github.com/yidas/jquery-freeze-table#update-for-dynamic-content))

Hope this will solve your problem.

Regards
Nick Tsai
