### ISSUE TITLE
Overlay freeze column shifts up on horizontal scroll

### ISSUE THREAD

**Issue by Cdenby** [yidas/js-freeze-table#9]
I have a table that has two trs in thead.
I need to freeze both of those rows and the first column.
I'm finding that the clone-head-table-wrap version of the table has the header taking up less vertical space and the first column shifts upwards.
I've done some measuring. Considering the cell addresses are A1, A2 (a la excel), here's what I see:
On the original table - the one that is displaying the content, 
A1 is 57x65 px
A2 is 57x81 px

On the clone-head-table-wrap, the cells are this measurement:
A1 is 94x33 (line-height 16.245px
A2 is 94x49

So with the drop from height of 65+81 down to 33+49, the rest of the first column is slid up so high that it is pretty much two cell heights off on the rest of the table.

I've gone through the inspection of cells A1 and A2 in both the original and the clone and the applicable settings all appear to be the same. But the height and width are not equal. Presumably, that's because the other columns in the cloned table are of different sizes and that's forcing the measurements of the visible frozen columns to be incorrect. I've tried to see if the measurements of the other columns of the table differ between the original and the clone but I'm unable to retrieve the hidden cell sizing.

I have a few media queries happening here to manage font size, but I wouldn't expect that to cause these issues.

Are there any ideas on this?

**Comment by Cdenby** [comment]
I may have found a work-around.
I've added the following after calling freezeTable
`setTimeout(function(){$(window).resize();}, 1000);`
There's still a bit of flickering that I wish wasn't there, but it means I can get this to work.
Fingers crossed that it works without issue ongoing.

**Comment by yidas** [comment]
Hi @Cdenby,

You can use `$('.freeze-table').freezeTable('resize');` instead of `$(window).resize();`.
